Task 4 3
greraldicus/Algos_Contest2_MIPT pull request #3
Opened 2021-11-28 07:22 UTC by greraldicus

2021-11-28 16:46 UTC, Davabbb commented
**переделывай**

2021-12-12 15:12 UTC, smatskevich requested changes

2021-12-12 15:12 UTC, smatskevich commented on TASK2_4/.idea/.gitignore
> +# Default ignored files
Лучше в корневой .gitignore добавить игнор всей папки .idea

2021-12-12 15:12 UTC, smatskevich commented on TASK2_4/.idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Эти все файлы папки .idea не нужны.

2021-12-12 15:12 UTC, smatskevich commented on TASK2_4/cmake-build-debug/CMakeCache.txt
> +# This is the CMakeCache file.
Этот файл и все в этой папке тоже не нужны в репозитории.

2021-12-12 15:12 UTC, smatskevich commented on TASK_4_3/main.cpp
> +
Лишняя пустая строка.

2021-12-12 15:12 UTC, smatskevich commented on TASK_4_3/main.cpp
> +#include <iostream>
Нужна ссылка на посылку в ЯКонтесте. Можно здесь ее оставлять.

2021-12-12 15:12 UTC, smatskevich commented on TASK_4_3/main.cpp
> +        else if (merge_left < mid) {
Можно было бы доходить до конца в отдельном цикле, так вроде меньше проверок было бы в сумме. Но можно и так оставить.

2021-12-12 15:12 UTC, smatskevich commented on TASK2_4/main.cpp
> +#include <iostream>
Не присылайте две задачи в одной ПРе, пожалуйста. На будущее.

2021-12-12 15:12 UTC, smatskevich commented on TASK2_4/main.cpp
> +#include <iostream>
Тоже нужна ссылка на посылку.

2021-12-12 15:12 UTC, smatskevich commented on TASK2_4/main.cpp
> +}
Оставляйте в конце файла пустую строку (одну).
Это мелочь, миниправило хорошего тона.
Иначе потом после добавления нового кода в конец файла, предыдущая строка без перевода будет восприниматься диффом как изменённая строка.

2021-12-12 15:15 UTC, Davabbb commented
ну ты даёшь Гриша........

2021-12-12 15:27 UTC, smatskevich commented
> ну ты даёшь Гриша........

Так, тут посторонние в приватном репозитории :)

2021-12-22 17:43 UTC, closed without merging